## Section A: Data Structures & Control Structures

##### 1.    Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [65]:
list_1=[1,4,2,3,5]
list_1

[1, 4, 2, 3, 5]

In [66]:
# 1. append()
list_1.append(60)
print("After append(60):", list_1)

After append(60): [1, 4, 2, 3, 5, 60]

In [67]:
# 2.pop()
list_1.pop()
print("After Pop():", list_1)

After Pop(): [1, 4, 2, 3, 5]

In [68]:
# 3. extend()
list_1.extend([70, 80])
print("After extend([70, 80]):", list_1)

After extend([70, 80]): [1, 4, 2, 3, 5, 70, 80]

In [69]:
# 4. insert()
list_1.insert(2, 25)   # Insert 25 at index 2
print("After insert(2, 25):", list_1)

After insert(2, 25): [1, 4, 25, 2, 3, 5, 70, 80]

In [70]:
# 5. remove()
list_1.remove(80)   # Remove value 40
print("After remove(80):", list_1)

After remove(80): [1, 4, 25, 2, 3, 5, 70]

In [71]:
# 6. index()
index_value = list_1.index(70)
print("Index of 70:", index_value)

Index of 70: 6

In [72]:
# 7. count()
count_value = list_1.count(70)
print("Count of 70:", count_value)

Count of 70: 1

In [73]:
# 8. sort()
list_1.sort()
print("After sort():", list_1)

After sort(): [1, 2, 3, 4, 5, 25, 70]

In [74]:
# 9. reverse()
list_1.reverse()
print("After reverse():", list_1)

After reverse(): [70, 25, 5, 4, 3, 2, 1]

In [75]:
# 10. clear()
list_1.clear()
print("After clear():", list_1)

After clear(): []

##### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [76]:
#Tuple Created
students = ("Ravi", "Anu", "Kiran")
print(students)

('Ravi', 'Anu', 'Kiran')

In [77]:
students[1] = "Priya"

TypeError: 'tuple' object does not support item assignment

#### Why
##### Because tuples are immutable (cannot be changed after creation).

##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [78]:
set_int={1,2,2,3,3,4,4,5,6,7,8,9}
type(set_int)

set

In [79]:
set_int

{1, 2, 3, 4, 5, 6, 7, 8, 9}

* A set does not allow duplicate values.
* Even though 2, 3, 4 were repeated, they appear only once in the output.

* Sets are unordered, so the order may vary when printed.

* Sets are mutable, but all elements must be unique.

##### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [80]:
person = {
    "name": "Ravi",
    "age": 22,
    "city": "Chennai"
}

print("Original Dictionary:", person)

Original Dictionary: {'name': 'Ravi', 'age': 22, 'city': 'Chennai'}

In [81]:
#Update the age
person["age"] = 23

In [82]:
#Add New Key 'Email'
person["email"] = "ravi@gmail.com"

##### Print the final dictionary

In [83]:
print("Final Dictionary: ",person)

Final Dictionary:  {'name': 'Ravi', 'age': 23, 'city': 'Chennai', 'email': 'ravi@gmail.com'}

##### 5 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [84]:
age=int(input("Enter your age: "))
if age>=18:
    print('You are eligible to vote')
else:
    print('you are not eligible to vote')

Enter your age:  1

you are not eligible to vote

##### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [85]:
marks=int(input("Enter you marks: "))
if marks>=90:
    print('A')
elif (marks>=75) and (marks <=89):
    print('B')
elif (marks>=50) and (marks <=74):
    print('C')
elif marks <50:
    print('Fail')

Enter you marks:  34

Fail

##### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [86]:
number=int(input('enter your number: '))
if number>0:
    print('Positive Number')
    
    if number % 2 == 0:
        print("It is also Even")
    else:
        print("It is Odd")

elif  number==0:
    print('Zero')
else:
    print('Negative number')

enter your number:  34

Positive Number
It is also Even

## Section B: Numpy

##### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [24]:
import numpy as np

In [25]:
#Scalar using np.array(5)
scalar=np.array(5)
scalar

array(5)

In [26]:
#A 1D array with values 1 to 5
one_arr=np.array([1,2,3,4,5])
print(one_arr)

[1 2 3 4 5]

In [27]:
# A 2D array with values from 10 to 60 in steps of 10
two_arr=np.arange(10,70,10).reshape(2,3)
print(two_arr)

[[10 20 30]
 [40 50 60]]

##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [28]:
random_arr=np.random.randint(0,101,(4,4))
random_arr

array([[82, 43, 94, 23],
       [47, 42, 76, 33],
       [29, 58, 17, 70],
       [58, 49,  1, 48]], dtype=int32)

##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [32]:
import pandas as pd

In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
data=pd.DataFrame(arr,columns=['A','B','C'])
data

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [38]:
data.shape

(3, 3)

## Section C: Exploring Pandas

##### 1.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [41]:
# Create DataFrame manually (10 rows)
data = {
    "Name": ["Ravi", "Anu", "Kiran", "Priya", "Arun","Divya", "Vijay", "Sneha", "Ravi", "Arun"],
    "Age": [22, 24, 23, 25, 26, 22, 27, 24, 22, 26],
    "City": ["Chennai", "Bangalore", "Hyderabad", "Chennai", "Mumbai", "Delhi", "Chennai", "Bangalore", "Chennai", "Mumbai"],
    "Salary": [30000, 35000, np.nan, 40000, 45000, 30000, 50000, np.nan, 30000, 45000]
}
df=pd.DataFrame(data,columns=['Name','Age','City','Salary'])
df

    Name  Age       City   Salary
0   Ravi   22    Chennai  30000.0
1    Anu   24  Bangalore  35000.0
2  Kiran   23  Hyderabad      NaN
3  Priya   25    Chennai  40000.0
4   Arun   26     Mumbai  45000.0
5  Divya   22      Delhi  30000.0
6  Vijay   27    Chennai  50000.0
7  Sneha   24  Bangalore      NaN
8   Ravi   22    Chennai  30000.0
9   Arun   26     Mumbai  45000.0

In [42]:
#Use .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [43]:
#Use .describe()
df.describe()

             Age        Salary
count  10.000000      8.000000
mean   24.100000  38125.000000
std     1.852926   7989.949043
min    22.000000  30000.000000
25%    22.250000  30000.000000
50%    24.000000  37500.000000
75%    25.750000  45000.000000
max    27.000000  50000.000000

In [51]:
#Select 'Name' and 'City' columns
df[["Name", "City"]]

    Name       City
0   Ravi    Chennai
1    Anu  Bangalore
2  Kiran  Hyderabad
3  Priya    Chennai
4   Arun     Mumbai
5  Divya      Delhi
6  Vijay    Chennai
7  Sneha  Bangalore
8   Ravi    Chennai
9   Arun     Mumbai

In [53]:
# Drop 'City' column
df.drop('City',axis=1)

    Name  Age   Salary
0   Ravi   22  30000.0
1    Anu   24  35000.0
2  Kiran   23      NaN
3  Priya   25  40000.0
4   Arun   26  45000.0
5  Divya   22  30000.0
6  Vijay   27  50000.0
7  Sneha   24      NaN
8   Ravi   22  30000.0
9   Arun   26  45000.0

In [59]:
# Fill any missing values in 'Salary' column with the mean
mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)
df

    Name  Age       City   Salary
0   Ravi   22    Chennai  30000.0
1    Anu   24  Bangalore  35000.0
2  Kiran   23  Hyderabad  38125.0
3  Priya   25    Chennai  40000.0
4   Arun   26     Mumbai  45000.0
5  Divya   22      Delhi  30000.0
6  Vijay   27    Chennai  50000.0
7  Sneha   24  Bangalore  38125.0
8   Ravi   22    Chennai  30000.0
9   Arun   26     Mumbai  45000.0

In [64]:
#Remove any duplicate rows
df.drop_duplicates(inplace=True)
df

    Name  Age       City   Salary
0   Ravi   22    Chennai  30000.0
1    Anu   24  Bangalore  35000.0
2  Kiran   23  Hyderabad  38125.0
3  Priya   25    Chennai  40000.0
4   Arun   26     Mumbai  45000.0
5  Divya   22      Delhi  30000.0
6  Vijay   27    Chennai  50000.0
7  Sneha   24  Bangalore  38125.0