# DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING_Assignment_9

In [36]:
import pandas as pd
import numpy as np

In [58]:
data=pd.read_csv('adult_with_headers.csv')

## Tasks:
### 1.	Handle missing values as per the best practices (imputation, removal, etc.).

In [59]:
#check data details
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None

In [60]:
# Check missing values
print(data.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [61]:
# Check hidden missing values
for col in data.columns:
    print(col, (data[col] == "?").sum())

age 0
workclass 0
fnlwgt 0
education 0
education_num 0
marital_status 0
occupation 0
relationship 0
race 0
sex 0
capital_gain 0
capital_loss 0
hours_per_week 0
native_country 0
income 0

The dataset was checked using .isnull() and for special symbols like "?". No missing values were found, so no imputation was required.

#### ●	Apply scaling techniques to numerical features

##### a.	Standard Scaling

In [62]:
num_data=data._get_numeric_data()
num_data.head()

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler=StandardScaler()
scaler_data=scaler.fit_transform(num_data)
scaler_df=pd.DataFrame(scaler_data,columns=num_data.columns,index=num_data.index)
scaler_df

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

Standard Scaling :

Standard Scaling converts data to mean = 0 and standard deviation = 1. It is preferred for normally distributed data and is commonly used in algorithms like Logistic Regression and SVM.

##### b. Min-Max Scaling

In [65]:
from sklearn.preprocessing import MinMaxScaler

In [66]:
scaler=MinMaxScaler()
scaler_data=scaler.fit_transform(num_data)
scaler_df=pd.DataFrame(scaler_data,columns=num_data.columns,index=num_data.index)
scaler_df

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.021740,0.0,0.397959
1,0.452055,0.048238,0.800000,0.000000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.000000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.000000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
32556,0.136986,0.166404,0.733333,0.000000,0.0,0.377551
32557,0.315068,0.096500,0.533333,0.000000,0.0,0.397959
32558,0.561644,0.094827,0.533333,0.000000,0.0,0.397959
32559,0.068493,0.128499,0.533333,0.000000,0.0,0.193878
32560,0.479452,0.187203,0.533333,0.150242,0.0,0.397959

Min-Max Scaling scales:
Min-Max Scaling scales data to a fixed range (0 to 1). It is preferred for non-normal data and is commonly used in KNN and Neural Networks.

### 2. Encoding Techniques:

#### ●	Apply One-Hot Encoding to categorical variables with less than 5 categories

In [67]:
# Select categorical columns
cat_cols = data.select_dtypes(include=['object']).columns

# One-Hot Encoding for columns with <5 unique values
low_card_cols = [col for col in cat_cols if data[col].nunique() < 5]
data1 = pd.get_dummies(data, columns=low_card_cols)  # creates binary columns
data1.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,False,True,True,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,False,True,True,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,False,True,True,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,False,True,True,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,True,False,True,False

#### ●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
#### ●	les with more than 5 categories

In [68]:
from sklearn.preprocessing import LabelEncoder
# Label Encoding for columns with >=5 unique values
high_card_cols = [col for col in cat_cols if data[col].nunique() >= 5]

le = LabelEncoder()
for col in high_card_cols:
    data1[col] = le.fit_transform(data1[col])  # converts categories to numbers
data1.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,7,77516,9,13,4,1,1,4,2174,0,40,39,False,True,True,False
1,50,6,83311,9,13,2,4,0,4,0,0,13,39,False,True,True,False
2,38,4,215646,11,9,0,6,1,4,0,0,40,39,False,True,True,False
3,53,4,234721,1,7,2,6,0,2,0,0,40,39,False,True,True,False
4,28,4,338409,9,13,2,10,5,2,0,0,40,5,True,False,True,False

#### ●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).

In [69]:
# Load dataset
df = pd.read_csv("adult_with_headers.csv")
# View first few rows
df.head()  # sample data

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [70]:
# Check data types and non-null values
df.info()  # structure of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [71]:
# Summary statistics
df.describe()  # mean, std, min, max

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

#### ●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

One-Hot Encoding:

Pros:
No ordinal relationship between categories

Suitable for small number of categories

Cons:
Increases number of columns (high dimensionality)

Can make model slowe

Label Encoding:

Pros:
Memory efficient

Suitable for large number of categories

Cons:
Introduces false order between categories

May affect model performance

### 3. Feature Engineering:

#### ●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.

In [81]:
# Feature 1: Income-Age Ratio
df['income_age_ratio'] = df['hours_per_week'] / (df['age'] + 1)
df['income_age_ratio']

0        1.000000
1        0.254902
2        1.025641
3        0.740741
4        1.379310
           ...
32556    1.357143
32557    0.975610
32558    0.677966
32559    0.869565
32560    0.754717
Name: income_age_ratio, Length: 32561, dtype: float64

In [85]:
# Feature 2: Capital Gain Indicator
df['has_capital_gain'] = (df['capital_gain'] > 0).astype(int)
df['has_capital_gain']

0        1
1        0
2        0
3        0
4        0
        ..
32556    0
32557    0
32558    0
32559    0
32560    1
Name: has_capital_gain, Length: 32561, dtype: int64

New features were created to improve model performance. Income-age ratio captures work intensity, and capital gain indicator simplifies financial information.

#### ●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [80]:
df['capital_gain'] = np.log1p(df['capital_gain'])
df['capital_gain']

0        2.161573
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...
32556    0.000000
32557    0.000000
32558    0.000000
32559    0.000000
32560    2.362501
Name: capital_gain, Length: 32561, dtype: float64

Log transformation was applied to reduce skewness in the capital_gain feature and improve model performance.